import { computed } from '/vendor/vue.esm-browser.prod.js';

export function useViewerProps(options) {
  const {
    layoutStyle,
    filters,
    roots,
    metadataFilterList,
    assets,
    selectedAsset,
    details,
    selectedPath,
    selectedPathSetHas,
    blurThumbnails,
    statusText,
    selectedCount,
    deleteCount,
    isLoading,
    isLoadingMore,
    isDeleting,
    hasMore,
    currentRootLabel,
    densityClass,
    assetListStyle,
    shouldVirtualize,
    visibleAssets,
    virtualSpacerStyle,
    virtualWindowStyle,
    setAssetListRef,
    setSearchInputRef,
    onAssetListScroll,
    refreshAssets,
    loadMore,
    selectAsset,
    clearSelection,
    copySelectedPaths,
    copySelectedTagName,
    exportSelectedAssets,
    openCompareSelection,
    requestDeleteSelected,
    requestDeleteAsset,
    hideDeleteConfirm,
    confirmDelete,
    safeDelete,
    startDetailsResize,
    startPreviewResize,
    openContainingFolder,
    repairSelectedMetadata,
    tagFilters,
    tagCategories,
    tagStatusText,
    tagCopyStatus,
    tagCountText,
    visibleTags,
    selectedTag,
    selectedTagAliases,
    selectedTagExamples,
    tagExamplesLoading,
    isLoadingTags,
    tagHasMore,
    isTagFavorite,
    fetchTags,
    selectTag,
    toggleTagFavorite,
    loadMoreTags,
    exampleImageUrl,
    tagSearchUrl,
    duplicateSettings,
    isScanningDuplicates,
    isCancellingDuplicateScan,
    duplicateStatusText,
    duplicateTaskId,
    duplicateTaskStatusText,
    duplicateCountText,
    duplicateScanProgress,
    duplicateScanPhase,
    duplicateScanProgressText,
    duplicateGroups,
    canCompareSelection,
    scanDuplicates,
    cancelDuplicateScan,
    selectAllDuplicateGroupsExcept,
    exportDuplicateGroups,
    selectDuplicateAsset,
    selectDuplicateGroupPaths,
    selectDuplicateGroupExcept,
    duplicateKindLabel,
    duplicateGroupSubtitle,
    markDuplicateThumbFailed,
    statsRootReports,
    isLoadingAnyFolderStats,
    isLoadingAnyMetadataHealth,
    fetchFolderStats,
    fetchMetadataHealth,
    fetchRootFolderStats,
    fetchRootMetadataHealth,
    exportMetadataHealth,
    settingsSections,
    settingsStatus,
    appVersion,
    appRepo,
    appReleasePageUrl,
    isCheckingUpdates,
    updateCheckStatus,
    checkForUpdatesNow,
    isSavingSettings,
    settingsFieldValue,
    settingsListValue,
    settingsListDraftValue,
    updateSettingsListDraft,
    updateSetting,
    updateStringListItem,
    addStringListSetting,
    removeStringListItem
  } = options;

  const assetsViewProps = computed(() => ({
    layoutStyle: layoutStyle.value,
    filters,
    roots: roots.value,
    metadataFilterList: metadataFilterList.value,
    assets: assets.value,
    selectedAsset: selectedAsset.value,
    details: details.value,
    selectedPath: selectedPath.value,
    selectedPathSetHas,
    blurThumbnails: blurThumbnails.value,
    statusText: statusText.value,
    selectedCount: selectedCount.value,
    deleteCount: deleteCount.value,
    isLoading: isLoading.value,
    isLoadingMore: isLoadingMore.value,
    isDeleting: isDeleting.value,
    hasMore: hasMore.value,
    currentRootLabel: currentRootLabel.value,
    densityClass: densityClass.value,
    assetListStyle: assetListStyle.value,
    shouldVirtualize: shouldVirtualize.value,
    visibleAssets: visibleAssets.value,
    virtualSpacerStyle: virtualSpacerStyle.value,
    virtualWindowStyle: virtualWindowStyle.value,
    assetListRef: setAssetListRef,
    searchInputRef: setSearchInputRef,
    onAssetListScroll,
    refreshAssets,
    loadMore,
    selectAsset,
    clearSelection,
    copySelectedPaths,
    exportSelectedAssets,
    openCompareSelection,
    requestDeleteSelected,
    requestDeleteAsset,
    hideDeleteConfirm,
    confirmDelete,
    safeDelete: safeDelete.value,
    startDetailsResize,
    startPreviewResize,
    openContainingFolder,
    repairSelectedMetadata
  }));

  const tagsViewProps = computed(() => ({
    layoutStyle: layoutStyle.value,
    tagFilters,
    tagCategories: tagCategories.value,
    tagStatusText: tagStatusText.value,
    tagCopyStatus: tagCopyStatus.value,
    tagCountText: tagCountText.value,
    visibleTags: visibleTags.value,
    selectedTag: selectedTag.value,
    selectedTagAliases: selectedTagAliases.value,
    selectedTagExamples: selectedTagExamples.value,
    tagExamplesLoading: tagExamplesLoading.value,
    isLoadingTags: isLoadingTags.value,
    tagHasMore: tagHasMore.value,
    isTagFavorite,
    fetchTags,
    selectTag,
    toggleTagFavorite,
    loadMoreTags,
    exampleImageUrl,
    tagSearchUrl,
    copySelectedTagName,
    startDetailsResize
  }));

  const duplicatesViewProps = computed(() => ({
    layoutStyle: layoutStyle.value,
    roots: roots.value,
    filters,
    duplicateSettings,
    isScanningDuplicates: isScanningDuplicates.value,
    isCancellingDuplicateScan: isCancellingDuplicateScan.value,
    duplicateStatusText: duplicateStatusText.value,
    duplicateTaskId: duplicateTaskId.value,
    duplicateTaskStatusText: duplicateTaskStatusText.value,
    duplicateCountText: duplicateCountText.value,
    duplicateScanProgress: duplicateScanProgress.value,
    duplicateScanPhase: duplicateScanPhase.value,
    duplicateScanProgressText: duplicateScanProgressText.value,
    duplicateGroups: duplicateGroups.value,
    canCompareSelection: canCompareSelection.value,
    selectedCount: selectedCount.value,
    deleteCount: deleteCount.value,
    isDeleting: isDeleting.value,
    selectedPathSetHas,
    scanDuplicates,
    cancelDuplicateScan,
    openCompareSelection,
    selectAllDuplicateGroupsExcept,
    copySelectedPaths,
    exportDuplicateGroups,
    requestDeleteSelected,
    clearSelection,
    selectDuplicateAsset,
    selectDuplicateGroupPaths,
    selectDuplicateGroupExcept,
    duplicateKindLabel,
    duplicateGroupSubtitle,
    markDuplicateThumbFailed,
    startDetailsResize
  }));

  const statsViewProps = computed(() => ({
    layoutStyle: layoutStyle.value,
    statsRootReports: statsRootReports.value,
    isLoadingAnyFolderStats: isLoadingAnyFolderStats.value,
    isLoadingAnyMetadataHealth: isLoadingAnyMetadataHealth.value,
    fetchFolderStats,
    fetchMetadataHealth,
    fetchRootFolderStats,
    fetchRootMetadataHealth,
    exportMetadataHealth
  }));

  const settingsViewProps = computed(() => ({
    layoutStyle: layoutStyle.value,
    settingsSections: settingsSections.value,
    settingsStatus: settingsStatus.value,
    appVersion: appVersion.value,
    appRepo: appRepo.value,
    appReleasePageUrl: appReleasePageUrl.value,
    isCheckingUpdates: isCheckingUpdates.value,
    updateCheckStatus: updateCheckStatus.value,
    checkForUpdatesNow,
    isSavingSettings: isSavingSettings.value,
    settingsFieldValue,
    settingsListValue,
    settingsListDraftValue,
    updateSettingsListDraft,
    updateSetting,
    updateStringListItem,
    addStringListSetting,
    removeStringListItem
  }));

  return {
    assetsViewProps,
    tagsViewProps,
    duplicatesViewProps,
    statsViewProps,
    settingsViewProps
  };
}
